### ISSUE TITLE
ERROR in app: Exception

### ISSUE THREAD

**Issue by dmitryint** [Energy1190/flask-web-rancher#13]
14.11.2017 15:11:12[2017-11-14 12:11:12,512] ERROR in app: Exception on /detail/1st70 [GET]
14.11.2017 15:11:12Traceback (most recent call last):
14.11.2017 15:11:12  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
14.11.2017 15:11:12    response = self.full_dispatch_request()
14.11.2017 15:11:12  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
14.11.2017 15:11:12    rv = self.handle_user_exception(e)
14.11.2017 15:11:12  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
14.11.2017 15:11:12    reraise(exc_type, exc_value, tb)
14.11.2017 15:11:12  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
14.11.2017 15:11:12    raise value
14.11.2017 15:11:12  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
14.11.2017 15:11:12    rv = self.dispatch_request()
14.11.2017 15:11:12  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
14.11.2017 15:11:12    return self.view_functions[rule.endpoint](**req.view_args)
14.11.2017 15:11:12  File "./app.py", line 45, in wrapper
14.11.2017 15:11:12    x = func(*args, q_args=args_r, **kwargs)
14.11.2017 15:11:12  File "./app.py", line 73, in detail_stack
14.11.2017 15:11:12    if answ_json: return jsonify((r, detail))
14.11.2017 15:11:12  File "/usr/local/lib/python3.6/site-packages/flask/json.py", line 263, in jsonify
14.11.2017 15:11:12    (dumps(data, indent=indent, separators=separators), '\n'),
14.11.2017 15:11:12  File "/usr/local/lib/python3.6/site-packages/flask/json.py", line 123, in dumps
14.11.2017 15:11:12    rv = _json.dumps(obj, **kwargs)
14.11.2017 15:11:12  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
14.11.2017 15:11:12    **kw).encode(obj)
14.11.2017 15:11:12  File "/usr/local/lib/python3.6/json/encoder.py", line 201, in encode
14.11.2017 15:11:12    chunks = list(chunks)
14.11.2017 15:11:12  File "/usr/local/lib/python3.6/json/encoder.py", line 428, in _iterencode
14.11.2017 15:11:12    yield from _iterencode_list(o, _current_indent_level)
14.11.2017 15:11:12  File "/usr/local/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
14.11.2017 15:11:12    yield from chunks
14.11.2017 15:11:12  File "/usr/local/lib/python3.6/json/encoder.py", line 437, in _iterencode
14.11.2017 15:11:12    o = _default(o)
14.11.2017 15:11:12  File "/usr/local/lib/python3.6/site-packages/flask/json.py", line 80, in default
14.11.2017 15:11:12    return _json.JSONEncoder.default(self, o)
14.11.2017 15:11:12  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
14.11.2017 15:11:12    o.__class__.__name__)
14.11.2017 15:11:12TypeError: Object of type 'RancherAPI' is not JSON serializable
14.11.2017 15:11:1210.42.119.2 - - [14/Nov/2017 12:11:12] "GET /detail/1st70 HTTP/1.1" 500 -
14.11.2017 15:11:1910.42.119.2 - - [14/Nov/2017 12:11:19] "GET / HTTP/1.1" 200 -
14.11.2017 15:11:26[2017-11-14 12:11:26,910] ERROR in app: Exception on /detail/test01 [GET]
14.11.2017 15:11:26Traceback (most recent call last):
14.11.2017 15:11:26  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
14.11.2017 15:11:26    response = self.full_dispatch_request()
14.11.2017 15:11:26  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
14.11.2017 15:11:26    rv = self.handle_user_exception(e)
14.11.2017 15:11:26  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
14.11.2017 15:11:26    reraise(exc_type, exc_value, tb)
14.11.2017 15:11:26  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
14.11.2017 15:11:26    raise value
14.11.2017 15:11:26  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
14.11.2017 15:11:26    rv = self.dispatch_request()
14.11.2017 15:11:26  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
14.11.2017 15:11:26    return self.view_functions[rule.endpoint](**req.view_args)
14.11.2017 15:11:26  File "./app.py", line 45, in wrapper
14.11.2017 15:11:26    x = func(*args, q_args=args_r, **kwargs)
14.11.2017 15:11:26  File "./app.py", line 71, in detail_stack
14.11.2017 15:11:26    x = r.get_stack(name)
14.11.2017 15:11:26  File "/app/classes.py", line 58, in wrap
14.11.2017 15:11:26    if self.key and self.secret: x = func(self, auth=HTTPBasicAuth(self.key, self.secret), *args, **kwargs)
14.11.2017 15:11:26  File "/app/classes.py", line 48, in wrap
14.11.2017 15:11:26    x = func(self, *args, **kwargs)
14.11.2017 15:11:26  File "/app/classes.py", line 66, in wrap
14.11.2017 15:11:26    if x.get('id'): self.id = x.get('id')
14.11.2017 15:11:26AttributeError: 'NoneType' object has no attribute 'get'
14.11.2017 15:11:2610.42.119.2 - - [14/Nov/2017 12:11:26] "GET /detail/test01 HTTP/1.1" 500 -
C

**Comment by Energy1190** [comment]
Скорее всего stack не был найден, или с него кто-то снял group. Это воспроизвести можно?

**Comment by dmitryint** [comment]
`curl -H "Accept: application/json" -X GET http://mgmt.webapp.appfurnish.com/detail/1st70`


не порти там ничего только

**Comment by Energy1190** [comment]
https://github.com/Energy1190/flask-web-rancher/pull/18

**Comment by Energy1190** [comment]
Но у тебя тут есть и не правильный запрос, если указать /detail/<имя сервиса> - будет ошибка, нужно /detail/<id сервиса>
